import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./componets/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
=======
      <body className={inter.className}>{children}</body>
      
    </html>
    </>
  )
>>>>>>> 028e1d77edfecc8effae9e748687e4ed085cc95c
}
